spring:
  application:
    name: department
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb/${MONGO_DATABASE}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true

spring.boot.admin.client.url: "http://admin:8080" 
spring.boot.admin.client.instance.prefer-ip: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
